spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.18.128:5432/josense
    username: postgres
    password: Douyulife
    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 100
      maxWait: 60000
      validationQuery: SELECT 1
      filters: stat,wall
handlebars:
  cache: false  # 生产环境，需要把这个设为true