spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mariadb://192.168.18.128:3306/josense
    username: root
    password: ad35667
    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 100
      maxWait: 60000
      validationQuery: SELECT 1
      filters: stat,wall
account:
  username: admin
  password: admin@123